### ISSUE TITLE
ruby-aws 1.5 vs. 1.6

### ISSUE THREAD

**Issue by srubin** [twitter-archive/clockworkraven#24]
When I was installing Clockwork Raven, I needed to manually install ruby-aws 1.5 by grabbing the gem from [here](http://rubygems.org/gems/ruby-aws/versions/1.5.0). I had to do this because the `bundle install` couldn't find ruby-aws 1.5, and installing ruby-aws 1.6 gave me errors when I ran rake tasks: 

```
uninitialized constant Amazon
clockworkraven/lib/m_turk_utils.rb:37:in `init_prod'
```

Everything works fine once I install 1.5, but I'm just warning you that this no longer seems to be grabbed by default via bundle/gem.

**Comment by echen** [comment]
Thanks for filing! This is actually fixed in the 0.2.0-wip branch (which we should go ahead and merge into master soon).
